import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

// we are going to change the font later
const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          {/* header */}
          <Header />
          <main className="min-h-screen">{children}</main>

          {/* footer */}
          <footer className="bg-blue-200 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>Made by anjany</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
